services:
  - type: web
    name: academia-financeiro
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    preDeployCommand: flask --app wsgi.py db upgrade
    startCommand: gunicorn wsgi:app
    healthCheckPath: /
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        sync: false
